### ISSUE TITLE
Planos de Conta Simplificado Trust-Code trust_l10n_br 

### ISSUE THREAD

**Issue by buguelos** [Trust-Code/trust-addons#16]
sempre da erro ao tentar instalar o modulo 

 raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Carregamento do M\xf3dulo trust_l10n_br falhou: arquivo trust_l10n_br/data/account.account.template.csv n\xe3o pode ser processado:
 Line 3 : null value in column "user_type" violates not-null constraint
DETAIL:  Failing row contains (728, 1, 1.1, 2016-06-17 13:26:26.765351, Ativo Circulante, null, null, null, null, 1, null, 727, f, 2016-06-17 13:26:26.765351, f, null).

**Comment by danimaribeiro** [comment]
Não está finalizado ainda.

**Comment by buguelos** [comment]
Fiz algumas modificações aqui consegui instalar não sei se foi correto mais me parece que subiu todos os dados utilizei o modelo e coloquei no plano de contas padrão!! vou testando pelo trabalho de vocês sem duvidas são os melhores!!! Obrigado Danima Ribeiro!

**Comment by danimaribeiro** [comment]
Eu acho que tu vai ter que corrigir essas duas colunas:

"type" e "user_type:id"  elas são muito importantes.

Envia a tua correção aqui para nós.

**Comment by danimaribeiro** [comment]
Corrigido já.
https://github.com/Trust-Code/trust-addons/commit/2f3f855b54648acd107f236aaa372906cea62320
